### ISSUE TITLE
Avant Garde font does not appear on displays.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-common#67]
Steps to reproduce:
1. Add Google Spreadsheet or Text Widget to a presentation
2. Add text in Avant Garde font
3. Save and publish presentation
4. Assign presentation to a display

Result:
Any content that should be displayed in the Avant Garde font will only appear as Arial (default). 

How it should work:
Avant Garde should appear on displays.

Demo Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=be88c7b0-4e33-44c6-8c74-b3dccde39f70

OS:
OSX, Windows, Linux

Chrome Ver:
42.0.2311.90 (64-bit)

Link to overview video:
http://www.screencast.com/t/xDxJkOpML

**Comment by btfrise** [comment]
FYI @stulees I have discovered that I am able upload a copy of an Avant Garde font in .otf format to my storage, then use it as a custom font in the presentation.

Given that I believe this should be a very low priority bug. Do you concur @alanclayton ?

**Comment by alanclayton** [comment]
@btfrise Agreed.

**Comment by alanclayton** [comment]
@stulees @donnapep @rodrigopavezi is this issue fixed with latest Text Widget?

**Comment by donnapep** [comment]
@alanclayton There is no Avant Garde font in the new font picker.

**Comment by alanclayton** [comment]
Won't fix given Donna's last comment.
